#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = ROOT / "rules"
CLASH_RULESETS_DIR = ROOT / "mihomo" / "rules"
QX_FILTER_PATH = ROOT / "quantumultx" / "filter" / "repo.snippet"
LOON_RULES_DIR = ROOT / "loon" / "rules"
SURGE_RULES_DIR = ROOT / "surge" / "rules"
LOCAL_RULES_MANIFEST = RULES_DIR / "local_rules.yaml"
# Configuration manifests live beside rule payloads but must not be parsed as rules.
RULE_METADATA_FILES = {"local_rules.yaml", "upstreams.yaml"}

RULE_TYPES = (
    ("domain_suffix", "DOMAIN-SUFFIX", "host-suffix"),
    ("domain", "DOMAIN", "host"),
    ("domain_keyword", "DOMAIN-KEYWORD", "host-keyword"),
    ("domain_regex", "DOMAIN-REGEX", "host-regex"),
    ("ip_cidr", "IP-CIDR", "ip-cidr"),
    ("ip_cidr6", "IP-CIDR6", "ip6-cidr"),
)
# Loon's domain rules are DOMAIN, DOMAIN-SUFFIX and DOMAIN-KEYWORD only; Surge has no
# DOMAIN-REGEX either, so both lists are rendered the same way.
LOON_UNSUPPORTED = {"domain_regex"}
# Surge's pre-matching REJECT lists run before every other rule, so they would also block
# subdomains that the bank and broker lists route on QX and Loon. reject_allow.list is the
# exclusion inside those REJECT rules; it is built from these sources, never edited by hand.
SURGE_REJECT_ALLOW_SOURCES = ("hk_banks.yaml", "intl_brokers.yaml")
SURGE_REJECT_ALLOW_TYPES = ("domain_suffix", "domain")

# Groups that switch with the network on QX and Loon. Rules point at "<group> · 自动", an ssid
# group that is DIRECT on the home Wi-Fi (the router proxies) and <group> elsewhere. Both
# bootstrap templates list these wrappers last, in this order. DIRECT, REJECT and 🛡️ 安全防护 are
# not wrapped, so ad blocking still rejects at home.
HOME_AUTO_SUFFIX = " · 自动"
HOME_AUTO_GROUPS = (
    "🤖 人工智能",
    "🎬 流媒体",
    "🎮 游戏平台",
    "🌐 社交平台",
    "🎙️ 商务协作",
    "👨‍💻 开发服务",
    "💰 加密货币",
    "🛒 电商支付",
    "🍎 苹果服务",
    "🌌 谷歌服务",
    "Ⓜ️ 微软服务",
    "📺 哔哩哔哩",
    "🇨🇳 国内服务",
    "📡 网络测速",
    "🐟 兜底分流",
    "🇭🇰 香港节点",
)


def home_auto(policy: str) -> str:
    """The policy a QX or Loon rule uses for a group: its "· 自动" wrapper if it has one."""
    return policy + HOME_AUTO_SUFFIX if policy in HOME_AUTO_GROUPS else policy


def load_manifest() -> list[dict[str, str]]:
    data = yaml.safe_load(LOCAL_RULES_MANIFEST.read_text(encoding="utf-8")) or {}
    items = data.get("rule_sets")
    if not isinstance(items, list):
        raise ValueError(f"{LOCAL_RULES_MANIFEST} must contain a 'rule_sets' list")

    configs: list[dict[str, str]] = []
    required = {"id", "title", "source", "clash_policy", "qx_policy"}
    for item in items:
        if not isinstance(item, dict):
            raise ValueError(f"{LOCAL_RULES_MANIFEST} contains a non-mapping rule set")
        missing = sorted(required - set(item))
        if missing:
            raise ValueError(
                f"{LOCAL_RULES_MANIFEST} rule set {item!r} is missing keys: {', '.join(missing)}"
            )
        configs.append({key: str(item[key]) for key in required})
    return configs


def load_rule_source(name: str) -> dict[str, list[str]]:
    path = RULES_DIR / name
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a mapping at top level")

    allowed = {key for key, _, _ in RULE_TYPES}
    unknown = sorted(set(data) - allowed)
    if unknown:
        raise ValueError(f"{path} contains unsupported rule types: {', '.join(unknown)}")

    normalized: dict[str, list[str]] = {}
    for key, value in data.items():
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            raise ValueError(f"{path} field '{key}' must be a list of strings")
        normalized[key] = value
    return normalized


def iter_rules(data: dict[str, list[str]]):
    for key, clash_token, qx_token in RULE_TYPES:
        for value in data.get(key, []):
            yield clash_token, qx_token, value


def render_clash_ruleset(rule_id: str, source_name: str, data: dict[str, list[str]]) -> str:
    payload = [f"{clash_token},{value}" for clash_token, _, value in iter_rules(data)]
    lines = [
        "# Generated by scripts/build_rules.py. Do not edit by hand.",
        f"# Source: rules/{source_name}",
        "payload:",
    ]
    lines.extend(f"  - {entry}" for entry in payload)
    return "\n".join(lines) + "\n"


def render_loon_list(source_name: str, data: dict[str, list[str]], client: str = "Loon") -> str:
    unsupported = sorted(LOON_UNSUPPORTED & {key for key, values in data.items() if values})
    if unsupported:
        raise ValueError(f"rules/{source_name}: {client} does not support {', '.join(unsupported)}")
    lines = [
        "# Generated by scripts/build_rules.py. Do not edit by hand.",
        f"# Source: rules/{source_name}",
    ]
    lines.extend(f"{clash_token},{value}" for clash_token, _, value in iter_rules(data))
    return "\n".join(lines) + "\n"


def render_surge_reject_allow() -> str:
    lines = [
        "# Generated by scripts/build_rules.py. Do not edit by hand.",
        "# Sources: " + ", ".join(f"rules/{name}" for name in SURGE_REJECT_ALLOW_SOURCES),
        "# Hosts excluded from the Surge pre-matching REJECT lists (surge/modules/home-direct.sgmodule).",
    ]
    seen: set[str] = set()
    for name in SURGE_REJECT_ALLOW_SOURCES:
        data = load_rule_source(name)
        other = sorted(key for key, values in data.items() if values and key not in SURGE_REJECT_ALLOW_TYPES)
        if other:
            raise ValueError(f"rules/{name}: reject_allow.list only takes domain rules, got {', '.join(other)}")
        for clash_token, _, value in iter_rules(data):
            line = f"{clash_token},{value}"
            if line not in seen:
                seen.add(line)
                lines.append(line)
    return "\n".join(lines) + "\n"


def render_qx_filter() -> str:
    manifest = load_manifest()
    lines = [
        "# Generated by scripts/build_rules.py. Do not edit by hand.",
        "# Edit rules/*.yaml and rules/local_rules.yaml, then rerun this script.",
        "",
    ]
    for item in manifest:
        data = load_rule_source(item["source"])
        lines.append(f"# {item['title']}")
        for _, qx_token, value in iter_rules(data):
            lines.append(f"{qx_token}, {value}, {home_auto(item['qx_policy'])}")
        lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def build_outputs() -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for item in load_manifest():
        data = load_rule_source(item["source"])
        outputs[CLASH_RULESETS_DIR / f"{item['id']}.yaml"] = render_clash_ruleset(
            item["id"], item["source"], data
        )
        outputs[LOON_RULES_DIR / f"{item['id']}.list"] = render_loon_list(item["source"], data)
        outputs[SURGE_RULES_DIR / f"{item['id']}.list"] = render_loon_list(item["source"], data, "Surge")
    outputs[SURGE_RULES_DIR / "reject_allow.list"] = render_surge_reject_allow()
    outputs[QX_FILTER_PATH] = render_qx_filter()
    return outputs


def check_outputs(outputs: dict[Path, str]) -> int:
    mismatches: list[Path] = []
    for path, expected in outputs.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual != expected:
            mismatches.append(path)

    if mismatches:
        print("Generated files are out of date:", file=sys.stderr)
        for path in mismatches:
            print(f"  - {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Build shared Clash, Quantumult X, Loon and Surge rule artifacts.")
    parser.add_argument("--check", action="store_true", help="verify generated files are up to date")
    args = parser.parse_args()

    outputs = build_outputs()
    if args.check:
        return check_outputs(outputs)

    changed = [path for path, content in outputs.items() if write_if_changed(path, content)]
    if changed:
        print("Updated generated files:")
        for path in changed:
            print(f"  - {path.relative_to(ROOT)}")
    else:
        print("Generated files are already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
