#!/usr/bin/env python3
"""Build the Surge rewrite modules from pinned Surge modules.

Surge has no profile section that lists modules (unlike Loon's [Plugin]); each module is
installed and enabled per device. Each module enabled in the Loon setup becomes one repo module in
surge/modules/rewrite/, so the phone can switch apps on and off one by one. The earlier merged
module surge/modules/rewrite.sgmodule is still generated for its compatibility period.
Sources are either upstream Surge modules pinned to a commit or release tag, or frozen conversions
kept in surge/modules/converted/ (QX rewrites from ddgksf2013 and fmz200 that have no Surge version,
converted like loon/plugins/). Module arguments are applied here; the header records each source and its sha256. Scripts referenced
inside a module still follow that module's own URLs (kokoryh's point at its master branch, as
on Loon).

  python3 scripts/build_surge_modules.py          # fetch the pinned sources, write the modules
  python3 scripts/build_surge_modules.py --check  # regenerate and compare, no write

Exit codes: 0 ok / up to date, 1 out of date, 2 a source could not be fetched or parsed.
To update, change SOURCES (or a converted file), run the script, and review the diff.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# The merged module, kept for its compatibility period; the per-app modules replace it.
OUTPUT = ROOT / "surge" / "modules" / "rewrite.sgmodule"
MODULE_DIR = ROOT / "surge" / "modules" / "rewrite"
GENERATED = "# Generated by scripts/build_surge_modules.py. Do not edit by hand; change SOURCES there and rerun."

# Order follows the Loon [Plugin] list. Surge runs only the first matching http-response script
# and the first matching header-mode URL Rewrite, so keep app-specific modules before collections.
# That order holds inside the merged module only; Surge does not document the order between
# modules, so the per-app modules must not depend on it (tests/test_surge_config.py checks the
# MitM hosts they share). "file" names surge/modules/rewrite/<file>.sgmodule; "title" and "desc"
# become its #!name and #!desc.
SOURCES = (
    {
        "name": "kokoryh 哔哩哔哩增强",
        "file": "bilibili", "title": "哔哩哔哩增强", "desc": "哔哩哔哩去广告与增强，空降助手已关闭",
        "url": "https://raw.githubusercontent.com/kokoryh/Sparkle/"
        "1bc5b545a544d7d59b1cf821785daddc3868e4a5/release/surge/module/bilibili.sgmodule",
        # "#" is the author's off switch: it turns the sponsor-block script line into a comment
        # and passes sponsorBlock "#" to the protobuf script (same as the Loon pilot advice).
        "arguments": {"空降助手": "#"},
    },
    {
        # Loon uses Kelee's YouTube plugin, which is built on this module.
        "name": "Maasea YouTube (Music) Enhance",
        "file": "youtube", "title": "YouTube 增强", "desc": "YouTube 与 YouTube Music 去广告与增强",
        "url": "https://raw.githubusercontent.com/Maasea/sgmodule/"
        "65075cdb388fc5e3094afd7e7314c67b243f3525/YouTube.Enhance.sgmodule",
        "arguments": {},
    },
    # Kelee's Loon-only plugins for these apps are replaced by public QX rewrites from the
    # upstream authors (fmz200) or the ones the QX setup uses (ddgksf2013), converted and frozen.
    {
        "name": "fmz200 小红书", "path": "surge/modules/converted/Xiaohongshu.sgmodule",
        "file": "xiaohongshu", "title": "小红书去广告", "desc": "小红书去广告",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 高德地图", "path": "surge/modules/converted/AmapAds.sgmodule",
        "file": "amap", "title": "高德地图去广告", "desc": "高德地图去广告",
        "arguments": {},
    },
    {
        "name": "fmz200 知乎", "path": "surge/modules/converted/Zhihu.sgmodule",
        "file": "zhihu", "title": "知乎去广告", "desc": "知乎去广告",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 微信外链解锁", "path": "surge/modules/converted/UnblockURLinWeChat.sgmodule",
        "file": "wechat", "title": "微信外链解锁", "desc": "在微信内直接打开被拦截的外部链接",
        "arguments": {},
    },
    {
        "name": "blackmatrix7 Advertising",
        "file": "advertising", "title": "通用去广告", "desc": "blackmatrix7 的多 App 去广告改写",
        "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/"
        "5fe08949edb51935c67e0766dc4bc94c0dad0509/rewrite/Surge/Advertising/Advertising.sgmodule",
        "arguments": {},
    },
    {
        "name": "NSRingo iRingo Siri",
        "file": "siri", "title": "Siri 增强", "desc": "iRingo 的 Siri 与搜索增强",
        "url": "https://github.com/NSRingo/Siri/releases/download/v4.2.7/iRingo.Siri.sgmodule",
        "arguments": {},
    },
    {
        "name": "blackmatrix7 SafeRedirect",
        "file": "safe-redirect", "title": "安全重定向", "desc": "blackmatrix7 的安全重定向",
        "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/"
        "5fe08949edb51935c67e0766dc4bc94c0dad0509/rewrite/Surge/SafeRedirect/SafeRedirect.sgmodule",
        "arguments": {},
    },
    {
        "name": "app2smile Spotify",
        "file": "spotify", "title": "Spotify 增强", "desc": "Spotify 增强",
        "url": "https://raw.githubusercontent.com/app2smile/rules/"
        "df6366a7024e0b3f0aa3510c5b791eea6f3cba89/module/spotify.module",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 WeiboAds", "path": "surge/modules/converted/WeiboAds.sgmodule",
        "file": "weibo", "title": "微博去广告", "desc": "微博与微博国际版去广告",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 GoofishAds", "path": "surge/modules/converted/GoofishAds.sgmodule",
        "file": "goofish", "title": "闲鱼去广告", "desc": "闲鱼去广告",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 Douban", "path": "surge/modules/converted/Douban.sgmodule",
        "file": "douban", "title": "豆瓣网页增强", "desc": "豆瓣网页增强",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 Q-Search", "path": "surge/modules/converted/Q-Search.sgmodule",
        "file": "q-search", "title": "Safari 超级搜索", "desc": "Safari 超级搜索：搜索引擎设为 DuckDuckGo，用关键字前缀跳转到其他站点搜索",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 General", "path": "surge/modules/converted/General.sgmodule",
        "file": "general", "title": "神机重定向", "desc": "神机重定向，如 google.cn 跳转到 google.com",
        "arguments": {},
    },
)
# Sections a module may carry here. [General] and [MITM] are key = value sections whose
# %APPEND% values are merged; the others are line lists kept in source order.
KEYED_SECTIONS = ("General", "MITM")
LIST_SECTIONS = ("Rule", "URL Rewrite", "Header Rewrite", "Map Local", "Body Rewrite", "Script")
USER_AGENT = "proxy-config-surge-modules/1.0"


class SourceError(Exception):
    """A source could not be fetched, read or parsed."""


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            if response.status != 200:
                raise SourceError(f"{url}: HTTP {response.status}")
            return response.read()
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        raise SourceError(f"{url}: {exc}") from exc


def load(source: dict) -> tuple[str, bytes]:
    if "path" in source:
        try:
            return source["path"], (ROOT / source["path"]).read_bytes()
        except OSError as exc:
            raise SourceError(f"{source['path']}: {exc}") from exc
    return source["url"], fetch(source["url"])


def parse_arguments(text: str) -> dict[str, str]:
    for line in text.splitlines():
        match = re.match(r"^#!arguments\s*=\s*(.*)$", line)
        if match:
            pairs = {}
            for item in match.group(1).split(","):
                key, sep, value = item.partition(":")
                if not sep:
                    raise SourceError(f"cannot parse #!arguments item {item!r}")
                value = value.strip()
                if len(value) >= 2 and value[0] == value[-1] == '"':
                    value = value[1:-1]  # the module body already quotes these where needed
                pairs[key.strip()] = value
            return pairs
    return {}


def apply_arguments(text: str, name: str, overrides: dict[str, str]) -> str:
    values = parse_arguments(text)
    unknown = sorted(set(overrides) - set(values))
    if unknown:
        raise SourceError(f"{name}: unknown module arguments {unknown}")
    values.update(overrides)
    for key, value in values.items():
        text = text.replace("{{{" + key + "}}}", value)
    if "{{{" in text:
        raise SourceError(f"{name}: unreplaced placeholder {re.search(r'{{{[^}]*}}}', text).group(0)}")
    return text


def split_sections(text: str, name: str) -> dict[str, list[str]]:
    sections: dict[str, list[str]] = {}
    current = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            current = stripped[1:-1]
            if current not in KEYED_SECTIONS + LIST_SECTIONS:
                raise SourceError(f"{name}: unsupported section [{current}]")
            sections.setdefault(current, [])
        elif current is not None and stripped:
            sections[current].append(line.rstrip())
    return sections


def merge_keyed(sources: list[tuple[str, dict[str, list[str]]]], section: str) -> list[str]:
    merged: dict[str, list[str]] = {}
    for name, sections in sources:
        for line in sections.get(section, []):
            if line.lstrip().startswith("#"):
                continue
            key, sep, value = line.partition("=")
            value = value.strip()
            if not sep or not value.startswith("%APPEND%"):
                raise SourceError(f"{name}: [{section}] only takes 'key = %APPEND% ...' lines, got {line!r}")
            items = [v.strip() for v in value[len("%APPEND%"):].split(",") if v.strip()]
            bucket = merged.setdefault(key.strip(), [])
            bucket.extend(v for v in items if v not in bucket)
    return [f"{key} = %APPEND% {', '.join(values)}" for key, values in merged.items()]


def load_sources() -> list[tuple[dict, list[str], dict[str, list[str]]]]:
    """Each source with its provenance comment lines and its sections, arguments applied."""
    loaded = []
    for source in SOURCES:
        where, body = load(source)
        provenance = [
            f"# Source: {source['name']} {where}",
            f"#   sha256 {hashlib.sha256(body).hexdigest()}; arguments: "
            + (", ".join(f"{k}={v}" for k, v in source["arguments"].items()) or "defaults"),
        ]
        text = apply_arguments(body.decode("utf-8"), source["name"], source["arguments"])
        loaded.append((source, provenance, split_sections(text, source["name"])))

    names = [line.split("=", 1)[0].strip() for _, _, sections in loaded for line in sections.get("Script", [])
             if "=" in line and not line.lstrip().startswith("#")]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise SourceError(f"duplicate [Script] names across sources: {duplicates}")
    return loaded


def render_module(header: list[str], loaded: list[tuple[dict, list[str], dict[str, list[str]]]]) -> str:
    lines = header + ["", GENERATED] + [line for _, provenance, _ in loaded for line in provenance]
    parsed = [(source["name"], sections) for source, _, sections in loaded]
    for section in KEYED_SECTIONS[:1] + LIST_SECTIONS + KEYED_SECTIONS[1:]:
        if section in KEYED_SECTIONS:
            body = merge_keyed(parsed, section)
        else:
            body = []
            for name, sections in parsed:
                if sections.get(section):
                    if len(parsed) > 1:
                        body.append(f"# --- {name}")
                    body.extend(sections[section])
        if body:
            lines += ["", f"[{section}]", *body]
    return "\n".join(lines) + "\n"


def has_reject_rule(sections: dict[str, list[str]]) -> bool:
    return any(not line.lstrip().startswith("#") and ",REJECT" in line for line in sections.get("Rule", []))


def render() -> dict[Path, str]:
    """Every generated module by path: the merged module, then one module per source."""
    loaded = load_sources()
    outputs = {OUTPUT: render_module([
        "#!name=去广告与增强合集",
        "#!desc=把 Loon 中启用的插件合并为一个模块：哔哩哔哩（空降助手已关闭）、YouTube、小红书、高德地图、知乎、微信外链、"
        "blackmatrix7 去广告与安全重定向、Siri、Spotify，以及墨鱼的微博、闲鱼、豆瓣、Safari 超级搜索、神机重定向。需要 MitM。"
        "已拆分为单独的模块（分类 proxy-config），本模块在兼容期内保留，不要与拆分后的模块同时启用。",
        "#!category=proxy-config",
    ], loaded)}
    for entry in loaded:
        source, _, sections = entry
        desc = f"{source['desc']}。"
        if sections.get("MITM"):
            desc += "需要 MitM。"
        if has_reject_rule(sections):
            desc += "含拒绝规则，「在家直连 + 拦截」要排在本模块之后。"
        desc += "由仓库生成，不要与「去广告与增强合集」同时启用。"
        header = [f"#!name={source['title']}", f"#!desc={desc}", "#!category=proxy-config"]
        outputs[MODULE_DIR / f"{source['file']}.sgmodule"] = render_module(header, [entry])
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare with the committed modules (needs network)")
    args = parser.parse_args()
    try:
        outputs = render()
    except SourceError as exc:
        print(f"SOURCE ERROR: {exc}", file=sys.stderr)
        return 2
    stale = sorted(set(MODULE_DIR.glob("*.sgmodule")) - set(outputs))
    if args.check:
        changed = [path for path, content in outputs.items()
                   if not path.exists() or path.read_text(encoding="utf-8") != content]
        for path in changed + stale:
            print(f"{path.relative_to(ROOT)} is out of date", file=sys.stderr)
        if changed or stale:
            return 1
        print(f"{len(outputs)} Surge modules are up to date")
        return 0
    MODULE_DIR.mkdir(exist_ok=True)
    for path, content in outputs.items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        path.write_text(content, encoding="utf-8")
        print(f"Updated {path.relative_to(ROOT)}")
    for path in stale:
        path.unlink()
        print(f"Removed {path.relative_to(ROOT)}")
    print(f"{len(outputs)} Surge modules are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
