#!/usr/bin/env python3
"""Build the Surge rewrite modules from pinned Surge modules.

Surge has no profile section that lists modules (unlike Loon's [Plugin]); each module is
installed and enabled per device. Each module enabled in the Loon setup becomes one repo module in
surge/modules/rewrite/, so the phone can switch apps on and off one by one. Sources are either
upstream Surge modules pinned to a commit or release tag, or frozen conversions kept in
surge/modules/converted/ (QX rewrites from ddgksf2013 and fmz200 that have no Surge version,
converted like loon/plugins/). Module arguments are applied here; the header records each source
and its sha256. Scripts referenced inside a module still follow that module's own URLs (kokoryh's
point at its master branch, as on Loon).

  python3 scripts/build_surge_modules.py          # fetch the pinned sources, write the modules
  python3 scripts/build_surge_modules.py --check  # regenerate and compare, no write

Exit codes: 0 ok / up to date, 1 out of date, 2 a source could not be fetched or parsed.
To update, change SOURCES (or a converted file), run the script, and review the diff.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

from xiaoyuzhou_rewrites import preserve_features

ROOT = Path(__file__).resolve().parent.parent
MODULE_DIR = ROOT / "surge" / "modules" / "rewrite"
# fmz200/wool_scripts at the commit reviewed on 2026-10-05 (domestic app modules).
FMZ200 = "https://raw.githubusercontent.com/fmz200/wool_scripts/5d5f63fcf98bc69d5f8f1b1bae6f86a01ee4bb97"
GENERATED = "# Generated by scripts/build_surge_modules.py. Do not edit by hand; change SOURCES there and rerun."

# Order follows the Loon [Plugin] list. Surge runs only the first matching http-response script
# and the first matching header-mode URL Rewrite, and it does not document the order between
# modules, so the modules must not depend on each other's order (tests/test_surge_config.py checks
# the MitM hosts they share). "file" names surge/modules/rewrite/<file>.sgmodule; "title" and "desc"
# become its #!name and #!desc. "pins" replaces a mutable script URL inside an upstream module with
# the reviewed commit (each URL must appear exactly once).
SOURCES = (
    {
        "name": "kokoryh 哔哩哔哩增强",
        "file": "bilibili", "title": "哔哩哔哩增强", "desc": "哔哩哔哩去广告与增强，空降助手已关闭",
        "url": "https://raw.githubusercontent.com/kokoryh/Sparkle/"
        "1bc5b545a544d7d59b1cf821785daddc3868e4a5/release/surge/module/bilibili.sgmodule",
        # "#" is the author's off switch: it turns the sponsor-block script line into a comment
        # and passes sponsorBlock "#" to the protobuf script (same as the Loon pilot advice).
        "arguments": {"空降助手": "#"},
    },
    {
        # Loon uses Kelee's YouTube plugin, which is built on this module.
        "name": "Maasea YouTube (Music) Enhance",
        "file": "youtube", "title": "YouTube 增强", "desc": "YouTube 与 YouTube Music 去广告与增强",
        "url": "https://raw.githubusercontent.com/Maasea/sgmodule/"
        "65075cdb388fc5e3094afd7e7314c67b243f3525/YouTube.Enhance.sgmodule",
        "arguments": {},
    },
    # Kelee's Loon-only plugins for these apps are replaced by public QX rewrites from the
    # upstream authors (fmz200) or the ones the QX setup uses (ddgksf2013), converted and frozen.
    {
        "name": "fmz200 小红书", "path": "surge/modules/converted/Xiaohongshu.sgmodule",
        "file": "xiaohongshu", "title": "小红书去广告", "desc": "小红书去广告",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 高德地图", "path": "surge/modules/converted/AmapAds.sgmodule",
        "file": "amap", "title": "高德地图去广告", "desc": "高德地图去广告",
        "arguments": {},
    },
    {
        "name": "fmz200 知乎", "path": "surge/modules/converted/Zhihu.sgmodule",
        "file": "zhihu", "title": "知乎去广告", "desc": "知乎去广告",
        "arguments": {},
    },
    {
        # zZPiglet's original script (2026-10-05; it replaced ddgksf2013's repack). fmz200's module
        # loads it from master; its main branch is empty, so pin master's last commit.
        "name": "fmz200 WeChatUnlockLinkRestrict",
        "file": "wechat", "title": "微信外链解锁", "desc": "在微信内直接打开被拦截的外部链接",
        "url": f"{FMZ200}/Surge/module/split/partW/WeChatUnlockLinkRestrict.sgmodule",
        "pins": {
            "https://raw.githubusercontent.com/zZPiglet/Task/master/asset/UnblockURLinWeChat.js":
            "https://raw.githubusercontent.com/zZPiglet/Task/0a70fbe27dfb072dac29423d661ed3c47cf66aab/asset/UnblockURLinWeChat.js",
        },
        "arguments": {},
    },
    {
        "name": "blackmatrix7 Advertising",
        "file": "advertising", "title": "通用去广告", "desc": "blackmatrix7 的多 App 去广告改写",
        "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/"
        "5fe08949edb51935c67e0766dc4bc94c0dad0509/rewrite/Surge/Advertising/Advertising.sgmodule",
        "arguments": {},
    },
    {
        "name": "NSRingo iRingo Siri",
        "file": "siri", "title": "Siri 增强", "desc": "iRingo 的 Siri 与搜索增强",
        "url": "https://github.com/NSRingo/Siri/releases/download/v4.2.7/iRingo.Siri.sgmodule",
        "arguments": {},
    },
    {
        "name": "blackmatrix7 SafeRedirect",
        "file": "safe-redirect", "title": "安全重定向", "desc": "blackmatrix7 的安全重定向",
        "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/"
        "5fe08949edb51935c67e0766dc4bc94c0dad0509/rewrite/Surge/SafeRedirect/SafeRedirect.sgmodule",
        "arguments": {},
    },
    {
        "name": "app2smile Spotify",
        "file": "spotify", "title": "Spotify 增强", "desc": "Spotify 增强",
        "url": "https://raw.githubusercontent.com/app2smile/rules/"
        "df6366a7024e0b3f0aa3510c5b791eea6f3cba89/module/spotify.module",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 WeiboAds", "path": "surge/modules/converted/WeiboAds.sgmodule",
        "file": "weibo", "title": "微博去广告", "desc": "微博与微博国际版去广告",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 GoofishAds", "path": "surge/modules/converted/GoofishAds.sgmodule",
        "file": "goofish", "title": "闲鱼去广告", "desc": "闲鱼去广告",
        "arguments": {},
    },
    # Douban and General are no longer recommended (2026-10-05): kept generated, unchanged, until
    # every device has dropped them; General's only rule is also in blackmatrix7 SafeRedirect.
    {
        "name": "ddgksf2013 Douban", "path": "surge/modules/converted/Douban.sgmodule",
        "file": "douban", "title": "豆瓣网页增强", "desc": "豆瓣网页增强",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 Q-Search", "path": "surge/modules/converted/Q-Search.sgmodule",
        "file": "q-search", "title": "Safari 超级搜索", "desc": "Safari 超级搜索：搜索引擎设为 DuckDuckGo，用关键字前缀跳转到其他站点搜索",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 General", "path": "surge/modules/converted/General.sgmodule",
        "file": "general", "title": "神机重定向", "desc": "神机重定向，如 google.cn 跳转到 google.com",
        "arguments": {},
    },
    # Added 2026-10-05 for apps on the phone that blackmatrix7 Advertising barely covers.
    {
        "name": "ddgksf2013 NeteaseMailAds", "path": "surge/modules/converted/NeteaseMailAds.sgmodule",
        "file": "neteasemail", "title": "网易邮箱大师去广告", "desc": "网易邮箱大师去广告",
        "arguments": {},
    },
    {
        # fmz200's split module (2026-10-05; it replaced ddgksf2013's XiaoYuZhouAds), script-free.
        "name": "fmz200 XiaoYuZhou",
        "file": "xiaoyuzhou", "title": "小宇宙去广告", "desc": "小宇宙去广告",
        "url": f"{FMZ200}/Surge/module/split/partX/XiaoYuZhou.sgmodule",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 DaMaiAds", "path": "surge/modules/converted/DaMaiAds.sgmodule",
        "file": "damai", "title": "大麦去广告", "desc": "大麦去广告",
        "arguments": {},
    },
    {
        "name": "ddgksf2013 UmetripAds", "path": "surge/modules/converted/UmetripAds.sgmodule",
        "file": "umetrip", "title": "航旅纵横去广告", "desc": "航旅纵横去广告",
        "arguments": {},
    },
    {
        "name": "Maasea WeRead",
        "file": "weread", "title": "微信读书精简", "desc": "去除微信读书的小红点、小圈子提示和评论数等，不是去广告",
        "url": "https://raw.githubusercontent.com/Maasea/sgmodule/"
        "db50d23ecb3900ad1d945526de50290d6e1bb044/WeRead.sgmodule",
        # Same reviewed commit as loon/plugins/WeRead.plugin and quantumultx/rewrite/WeRead.conf.
        "pins": {
            "https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/WeRead/weread.js":
            "https://raw.githubusercontent.com/Maasea/sgmodule/2c2c0adba8454f16c82c05fe5ed415badcbdd3d8/Script/WeRead/weread.js",
        },
        "arguments": {},
    },    # Added 2026-10-05: fmz200 split modules for installed domestic apps, pinned to one commit. They have
    # no scripts (tests/test_surge_config.py checks), so nothing inside needs pinning.
    {
        "name": "fmz200 WeChatOfficialAccount",
        "file": "wechat-mp", "title": "微信公众号去广告", "desc": "微信公众号文章广告与商品推广",
        "url": f"{FMZ200}/Surge/module/split/partW/WeChatOfficialAccount.sgmodule",
        "arguments": {},
    },
    {
        "name": "fmz200 Meituan-MeituanWaimai",
        "file": "meituan", "title": "美团去广告", "desc": "美团与美团外卖的开屏和广告图；外卖开屏依赖通用去广告解密 wmapi.meituan.com",
        "url": f"{FMZ200}/Surge/module/split/partM/Meituan-MeituanWaimai.sgmodule",
        "arguments": {},
    },
    {
        "name": "fmz200 Hupu",
        "file": "hupu", "title": "虎扑去广告", "desc": "虎扑开屏、帖子与图片广告",
        "url": f"{FMZ200}/Surge/module/split/partH/Hupu.sgmodule",
        "arguments": {},
    },
    {
        "name": "fmz200 Mijia",
        "file": "mijia", "title": "米家去广告", "desc": "米家开屏与横幅",
        "url": f"{FMZ200}/Surge/module/split/partM/Mijia.sgmodule",
        "arguments": {},
    },
    {
        "name": "fmz200 MaoYan",
        "file": "maoyan", "title": "猫眼去广告", "desc": "猫眼开屏",
        "url": f"{FMZ200}/Surge/module/split/partM/MaoYan.sgmodule",
        "arguments": {},
    },
    {
        "name": "fmz200 LeKe",
        "file": "leke", "title": "乐刻去广告", "desc": "乐刻运动开屏与广告位",
        "url": f"{FMZ200}/Surge/module/split/partB/LeKe.sgmodule",
        "arguments": {},
    },
    {
        "name": "fmz200 Douban",
        "file": "douban-app", "title": "豆瓣 App 去广告", "desc": "豆瓣 App 广告；横幅与部分启动图所在主机没有解密，不在覆盖范围",
        "url": f"{FMZ200}/Surge/module/split/partD/Douban.sgmodule",
        "arguments": {},
    },
    {
        "name": "fmz200 ChinaMobile",
        "file": "chinamobile", "title": "中国移动去广告", "desc": "中国移动开屏与悬浮窗",
        "url": f"{FMZ200}/Surge/module/split/partZ/ChinaMobile.sgmodule",
        "arguments": {},
    },
)
# Sections a module may carry here. [General] and [MITM] are key = value sections whose
# %APPEND% values are merged; the others are line lists kept in source order.
KEYED_SECTIONS = ("General", "MITM")
LIST_SECTIONS = ("Rule", "URL Rewrite", "Header Rewrite", "Map Local", "Body Rewrite", "Script")
USER_AGENT = "proxy-config-surge-modules/1.0"


class SourceError(Exception):
    """A source could not be fetched, read or parsed."""


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            if response.status != 200:
                raise SourceError(f"{url}: HTTP {response.status}")
            return response.read()
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        raise SourceError(f"{url}: {exc}") from exc


def load(source: dict) -> tuple[str, bytes]:
    if "path" in source:
        try:
            return source["path"], (ROOT / source["path"]).read_bytes()
        except OSError as exc:
            raise SourceError(f"{source['path']}: {exc}") from exc
    return source["url"], fetch(source["url"])


def parse_arguments(text: str) -> dict[str, str]:
    for line in text.splitlines():
        match = re.match(r"^#!arguments\s*=\s*(.*)$", line)
        if match:
            pairs = {}
            for item in match.group(1).split(","):
                key, sep, value = item.partition(":")
                if not sep:
                    raise SourceError(f"cannot parse #!arguments item {item!r}")
                value = value.strip()
                if len(value) >= 2 and value[0] == value[-1] == '"':
                    value = value[1:-1]  # the module body already quotes these where needed
                pairs[key.strip()] = value
            return pairs
    return {}


def apply_arguments(text: str, name: str, overrides: dict[str, str]) -> str:
    values = parse_arguments(text)
    unknown = sorted(set(overrides) - set(values))
    if unknown:
        raise SourceError(f"{name}: unknown module arguments {unknown}")
    values.update(overrides)
    for key, value in values.items():
        text = text.replace("{{{" + key + "}}}", value)
    if "{{{" in text:
        raise SourceError(f"{name}: unreplaced placeholder {re.search(r'{{{[^}]*}}}', text).group(0)}")
    return text


def split_sections(text: str, name: str) -> dict[str, list[str]]:
    sections: dict[str, list[str]] = {}
    current = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            current = stripped[1:-1]
            if current not in KEYED_SECTIONS + LIST_SECTIONS:
                raise SourceError(f"{name}: unsupported section [{current}]")
            sections.setdefault(current, [])
        elif current is not None and stripped:
            sections[current].append(line.rstrip())
    return sections


def merge_keyed(sources: list[tuple[str, dict[str, list[str]]]], section: str) -> list[str]:
    merged: dict[str, list[str]] = {}
    for name, sections in sources:
        for line in sections.get(section, []):
            if line.lstrip().startswith("#"):
                continue
            key, sep, value = line.partition("=")
            value = value.strip()
            if not sep or not value.startswith("%APPEND%"):
                raise SourceError(f"{name}: [{section}] only takes 'key = %APPEND% ...' lines, got {line!r}")
            items = [v.strip() for v in value[len("%APPEND%"):].split(",") if v.strip()]
            bucket = merged.setdefault(key.strip(), [])
            bucket.extend(v for v in items if v not in bucket)
    return [f"{key} = %APPEND% {', '.join(values)}" for key, values in merged.items()]


def load_sources() -> list[tuple[dict, list[str], dict[str, list[str]]]]:
    """Each source with its provenance comment lines and its sections, arguments applied."""
    loaded = []
    for source in SOURCES:
        missing = sorted({"file", "title", "desc"} - set(source))
        if missing:
            raise SourceError(f"{source['name']}: missing {missing}")
        where, body = load(source)
        provenance = [
            f"# Source: {source['name']} {where}",
            f"#   sha256 {hashlib.sha256(body).hexdigest()}; arguments: "
            + (", ".join(f"{k}={v}" for k, v in source["arguments"].items()) or "defaults"),
        ]
        text = apply_arguments(body.decode("utf-8"), source["name"], source["arguments"])
        if source["file"] == "xiaoyuzhou":
            text = preserve_features(text)
            provenance.append("#   changes: preserve AI summaries, normal search, categories and recommendations")
        for old, new in source.get("pins", {}).items():
            if text.count(old) != 1:
                raise SourceError(f"{source['name']}: pin target {old} must appear exactly once")
            text = text.replace(old, new)
            provenance.append(f"#   script pinned: {new}")
        loaded.append((source, provenance, split_sections(text, source["name"])))

    names = [line.split("=", 1)[0].strip() for _, _, sections in loaded for line in sections.get("Script", [])
             if "=" in line and not line.lstrip().startswith("#")]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise SourceError(f"duplicate [Script] names across sources: {duplicates}")
    return loaded


def render_module(header: list[str], source: dict, provenance: list[str], sections: dict[str, list[str]]) -> str:
    lines = header + ["", GENERATED] + provenance
    for section in KEYED_SECTIONS[:1] + LIST_SECTIONS + KEYED_SECTIONS[1:]:
        if section in KEYED_SECTIONS:
            body = merge_keyed([(source["name"], sections)], section)
        else:
            body = sections.get(section, [])
        if body:
            lines += ["", f"[{section}]", *body]
    return "\n".join(lines) + "\n"


def has_reject_rule(sections: dict[str, list[str]]) -> bool:
    return any(not line.lstrip().startswith("#") and ",REJECT" in line for line in sections.get("Rule", []))


def render() -> dict[Path, str]:
    """Every generated module by path, one per source."""
    outputs = {}
    for source, provenance, sections in load_sources():
        desc = f"{source['desc']}。"
        if sections.get("MITM"):
            desc += "需要 MitM。"
        if has_reject_rule(sections):
            desc += "含拒绝规则，「在家直连 + 拦截」要排在本模块之后。"
        desc += "由仓库生成。"
        header = [f"#!name={source['title']}", f"#!desc={desc}", "#!category=proxy-config"]
        outputs[MODULE_DIR / f"{source['file']}.sgmodule"] = render_module(header, source, provenance, sections)
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare with the committed modules (needs network)")
    args = parser.parse_args()
    try:
        outputs = render()
    except SourceError as exc:
        print(f"SOURCE ERROR: {exc}", file=sys.stderr)
        return 2
    stale = sorted(set(MODULE_DIR.glob("*.sgmodule")) - set(outputs))
    if args.check:
        changed = [path for path, content in outputs.items()
                   if not path.exists() or path.read_text(encoding="utf-8") != content]
        for path in changed + stale:
            print(f"{path.relative_to(ROOT)} is out of date", file=sys.stderr)
        if changed or stale:
            return 1
        print(f"{len(outputs)} Surge modules are up to date")
        return 0
    MODULE_DIR.mkdir(exist_ok=True)
    for path, content in outputs.items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        path.write_text(content, encoding="utf-8")
        print(f"Updated {path.relative_to(ROOT)}")
    for path in stale:
        path.unlink()
        print(f"Removed {path.relative_to(ROOT)}")
    print(f"{len(outputs)} Surge modules are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
