#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = ROOT / "rules"
CLASH_RULESETS_DIR = ROOT / "clash" / "rulesets"
QX_FILTER_PATH = ROOT / "quantumultx" / "filter_remote.snippet"
LOCAL_RULES_MANIFEST = RULES_DIR / "local_rules.yaml"

RULE_TYPES = (
    ("domain_suffix", "DOMAIN-SUFFIX", "host-suffix"),
    ("domain", "DOMAIN", "host"),
    ("domain_keyword", "DOMAIN-KEYWORD", "host-keyword"),
    ("domain_regex", "DOMAIN-REGEX", "host-regex"),
    ("ip_cidr", "IP-CIDR", "ip-cidr"),
    ("ip_cidr6", "IP-CIDR6", "ip6-cidr"),
)


def load_manifest() -> list[dict[str, str]]:
    data = yaml.safe_load(LOCAL_RULES_MANIFEST.read_text(encoding="utf-8")) or {}
    items = data.get("rule_sets")
    if not isinstance(items, list):
        raise ValueError(f"{LOCAL_RULES_MANIFEST} must contain a 'rule_sets' list")

    configs: list[dict[str, str]] = []
    required = {"id", "title", "source", "clash_policy", "qx_policy"}
    for item in items:
        if not isinstance(item, dict):
            raise ValueError(f"{LOCAL_RULES_MANIFEST} contains a non-mapping rule set")
        missing = sorted(required - set(item))
        if missing:
            raise ValueError(
                f"{LOCAL_RULES_MANIFEST} rule set {item!r} is missing keys: {', '.join(missing)}"
            )
        configs.append({key: str(item[key]) for key in required})
    return configs


def load_rule_source(name: str) -> dict[str, list[str]]:
    path = RULES_DIR / name
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a mapping at top level")

    allowed = {key for key, _, _ in RULE_TYPES}
    unknown = sorted(set(data) - allowed)
    if unknown:
        raise ValueError(f"{path} contains unsupported rule types: {', '.join(unknown)}")

    normalized: dict[str, list[str]] = {}
    for key, value in data.items():
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            raise ValueError(f"{path} field '{key}' must be a list of strings")
        normalized[key] = value
    return normalized


def iter_rules(data: dict[str, list[str]]):
    for key, clash_token, qx_token in RULE_TYPES:
        for value in data.get(key, []):
            yield clash_token, qx_token, value


def render_clash_ruleset(rule_id: str, source_name: str, data: dict[str, list[str]]) -> str:
    payload = [f"{clash_token},{value}" for clash_token, _, value in iter_rules(data)]
    lines = [
        "# Generated by scripts/build_rules.py. Do not edit by hand.",
        f"# Source: rules/{source_name}",
        "payload:",
    ]
    lines.extend(f"  - {entry}" for entry in payload)
    return "\n".join(lines) + "\n"


def render_qx_filter() -> str:
    manifest = load_manifest()
    lines = [
        "# Generated by scripts/build_rules.py. Do not edit by hand.",
        "# Edit rules/*.yaml and rules/local_rules.yaml, then rerun this script.",
        "",
    ]
    for item in manifest:
        data = load_rule_source(item["source"])
        lines.append(f"# {item['title']}")
        for _, qx_token, value in iter_rules(data):
            lines.append(f"{qx_token}, {value}, {item['qx_policy']}")
        lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def build_outputs() -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for item in load_manifest():
        data = load_rule_source(item["source"])
        outputs[CLASH_RULESETS_DIR / f"{item['id']}.yaml"] = render_clash_ruleset(
            item["id"], item["source"], data
        )
    outputs[QX_FILTER_PATH] = render_qx_filter()
    return outputs


def check_outputs(outputs: dict[Path, str]) -> int:
    mismatches: list[Path] = []
    for path, expected in outputs.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual != expected:
            mismatches.append(path)

    if mismatches:
        print("Generated files are out of date:", file=sys.stderr)
        for path in mismatches:
            print(f"  - {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Build shared Clash and Quantumult X rule artifacts.")
    parser.add_argument("--check", action="store_true", help="verify generated files are up to date")
    args = parser.parse_args()

    outputs = build_outputs()
    if args.check:
        return check_outputs(outputs)

    changed = [path for path, content in outputs.items() if write_if_changed(path, content)]
    if changed:
        print("Updated generated files:")
        for path in changed:
            print(f"  - {path.relative_to(ROOT)}")
    else:
        print("Generated files are already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
